dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - ".typo-ci.yml"
  - ".devcontainer/*"
  - ".gitignore"

# Any typos we should ignore?
excluded_words:
  - devcontainer
  
# Would you like filenames to also be spellchecked?
spellcheck_filenames: true