dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - ".typo-ci.yml"
  - ".devcontainer/*"
  - ".gitignore"
  - ".github/*"
  - "docker/*"
  - "yarn.lock"
  - "tsconfig.base.json"


# Any typos we should ignore?
excluded_words:
  - devcontainer
  - ngrx
  - Softwares
  - iif
  - MemoizedSelector
  - tst
  - dgv
  - sft
  - graphql
  - pantoufle
  - pantoufl
  - xoverflow
  
# Would you like filenames to also be spellchecked?
spellcheck_filenames: true