version: 2
jobs:
  build:
    working_directory: ~/Dddependencies-graph-angular
    docker:
      - image: circleci/node:11.12-browsers
    steps:
      - checkout
      - run:
          name: Current branch
          command: echo ${CIRCLE_BRANCH} 
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Angular cli verion
          command: yarn ng version
      - run:
          name: Linting
          command: yarn ng lint
      - run:
          name: angular-build
          command: yarn ng build --prod --aot --verbose=true