# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Branche

# on: workflow_dispatch

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**/doc/**'
      - '**/README.md'
      - '**/LICENSE'
      - '**/.typo-ci.yml'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/steps/setiup

    - name: Unit Tests
      run: yarn ng test --watch=false --code-coverage --browsers=chromeNoSandbox

    - name: Build
      run: yarn ng build --prod --aot --no-progress

