# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    # branches: [ master ]
    paths-ignore:
      - '**/doc/**'
      - '**/README.md'
      - '**/LICENSE'
      - '**/.typo-ci.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/doc/**'
      - '**/README.md'
      - '**/LICENSE'
      - '**/.typo-ci.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.X'
      
    - name: Install dependencies
      run: yarn --frozen-lockfile
      
    - name: Lint
      run: yarn ng lint

    - name: Unit Tests
      run: yarn ng test --watch=false --code-coverage --browsers=chromeNoSandbox
    
    - name: update web driver
      run: yarn updateWebDriver --versions.chrome=83.0.4103.0

    # - name: e2e Tests
      # run: yarn e2e --configuration=ci
      
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build
      run: yarn ng build --prod --aot --no-progress
    
    - name: Build docker image
      run:  docker build . --tag dependencies-graph-view:test

