name: Release

on: [push]

jobs:

  docker-github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/download-artifact@v2
      with:
        name: dgv-site
        path: dist/

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.1.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/dependencies-graph-viewer:${{ steps.package-version.outputs.current-version }}
